@startuml board
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Editor Service" as e
database "Elements DB" as db
actor "Остальные пользователи\nна доске" as o

group 1. CRUD элементов на доске
u -> u : Выбирает, какое действие совершить
alt Create
u -> f : Выбирает элемент,\nкоторый хочет создать
f -> e : Посылает элемент, который\nпользователь хочет создать
e -> e : Создаёт элемент
e -> e : Сохраняет в историю\nизменений
e -> db : Сохраняет элемент
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -> f : Обновляет информацию\nу пользователя
end
f -> u : Показывает созданный элемент
else Update/Delete
u -> f : Выбирает элемент,\nкоторый хочет обновить
f -> u : Переводит пользователя\nв режим редактирования
u -> f : Вносит изменения\nв элемент
f -> e : Посылает элемент, который\n пользователь обновил
e -> e : Обновляет элемент
e -> e : Сохраняет в историю\nизменений
e -> db : Сохраняет изменения
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -> f : Обновляет информацию\nу пользователя
end
f -> u : Показывает обновленный элемент
end
end

@enduml