services:
    web:
        build: frontend/

        ports:
            - "3000:3000"
        depends_on:
            - server
            - user_db
    server:
        build: backend/
        depends_on:
            - user_db
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=user_db
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_PORT=5432
        volumes:
            - ./backend:/app_backend
        networks:
            - app-network
    user_db:
        image: postgres:17-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - app-network
        ports:
            - "5432:5432"
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:9
        environment:
            PGADMIN_DEFAULT_EMAIL: "mentalsmoge@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        depends_on:
            - user_db
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - app-network

volumes:
    postgres-data:
    pgadmin-data:
networks:
    app-network:
        driver: bridge
