version: "3"
services:
    web:
        build: frontend/
        ports:
            - "3000:3000"
        depends_on:
            - server
    server:
        build: backend/
        ports:
            - "8080:8080"
