@startuml sas
skinparam defaultFontSize 15
actor Пользователь as user
user -- (Создать проект)
(Создать проект) <.. (Создать доску) : расширить
user -- (Создать ссылку-приглашение в проект)
(Создать ссылку-приглашение в проект) <.. (Отправить приглашение через Telegram) : расширить
(Создать ссылку-приглашение в проект) <.. (Отправить приглашение внутри системы) : расширить
user -up- (Редактировать содержимое доски)
(Редактировать содержимое доски) <.up. (Группировать элементы доски) : расширить
(Редактировать содержимое доски) <.up. (Отменять изменения) : расширить
user -up- (Экспортировать данные)
(Экспортировать данные) <.up. (Экспортировать в .doc документе) : расширить
(Экспортировать данные) <.up. (Экспортировать в .md документе) : расширить
@enduml