apisix:
    node_listen: 9080
    enable_admin: true

deployment:
    admin:
        admin_key:
            - name: "admin"
              key: "admin123"
              role: admin

    etcd:
        host:
            - "http://etcd:2379"
