name: Backend CI/CD

on:
  push:
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'src/backend/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: src/backend/package-lock.json

    - name: Install dependencies
      working-directory: ./src/backend
      run: npm ci

    - name: Run unit tests
      working-directory: ./src/backend
      run: npm test

    - name: Build Docker image
      working-directory: ./src/backend
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest .

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest