name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  lint-test-build:
    name: Lint, Test & Build (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          'frontend',
          'ms_auth',
          'ms_api',
          'ms_editor',
          'ms_logs',
          'ms_notification',
          'ms_users'
        ]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd src/${{ matrix.service }}
          npm ci

      - name: Install dependencies2
        run: |
          cd src
          npm ci
          
      - name: Run ESLint
        if: ${{ always() }}
        run: |
          cd src
          npm run lint
          
      - name: Run TypeScript check
        if: ${{ matrix.service != 'frontend' && matrix.service != 'ms_logs' }}
        run: |
          cd src/${{ matrix.service }}
          if [ -f "tsconfig.json" ]; then
            npx tsc --noEmit
          fi
          
      - name: Run unit tests
        run: |
          cd src
            npm run unit-test
          
      - name: Run integration tests
        run: |
          cd src
            docker-compose -f ../../src/docker-compose.yml up -d kafka postgres redis rethink_db
            npm run int-test
          
          