name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  lint-test-build:
    name: Lint, Test & Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install root dependencies
        run: |
          cd src
          npm install
          
      - name: Install microservices dependencies
        run: |
          cd src
          for service in frontend ms_auth ms_api ms_editor ms_logs ms_notification ms_users; do
            echo "Installing dependencies for $service"
            cd $service && npm install && cd ..
          done
          
      - name: Run ESLint
        run: |
          cd src
          npm run lint
          
      - name: Run unit tests
        run: |
          cd src
          npm run test:unit
          