name: Frontend CI/CD

on:
  push:
    paths:
      - 'src/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'src/frontend/**'

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./src/frontend
      run: npm ci

    - name: Run tests
      working-directory: ./src/frontend
      run: npm test

    - name: Build Docker image
      working-directory: ./src/frontend
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest