name: Integration Tests

on:
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'postgres/**'
      - 'docker-compose.yml'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: userdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start infrastructure
      run: docker-compose up -d postgres

    - name: Initialize database
      run: |
        sleep 10
        psql -h user_db -U postgres -d userdb -f postgres/init.sql

    - name: Setup backend
      working-directory: ./backend
      run: |
        npm ci
        npm run build

    - name: Run integration tests
      working-directory: ./backend
      env:
        DB_HOST: user_db
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: userdb
        RETHINKDB_HOST: rethink_db
        RETHINKDB_PORT: 28015
        RETHINKDB_NAME: rethink


      run: npm run test:integration